@extends('admin.layout')

@section('title', 'Site settings')

@section('content')
    <div class="page-heading"><div><span class="sidebar-label">PORTFOLIO CONFIGURATION</span><h1>Site settings</h1><p>Update your profile, links, homepage copy, and search metadata.</p></div></div>
    <form class="admin-form settings-form" method="POST" action="{{ route('admin.settings.update') }}">@csrf @method('PUT')
        <section class="admin-panel"><div class="panel-heading"><div><span class="sidebar-label">IDENTITY</span><h2>Profile and homepage</h2></div></div><label for="site_title">Site title</label><input id="site_title" name="site_title" value="{{ old('site_title', $settings['site_title'] ?? '') }}" required>@error('site_title')<span class="field-error">{{ $message }}</span>@enderror<label for="hero_title">Hero headline</label><input id="hero_title" name="hero_title" value="{{ old('hero_title', $settings['hero_title'] ?? '') }}" required>@error('hero_title')<span class="field-error">{{ $message }}</span>@enderror<label for="hero_intro">Hero introduction</label><textarea id="hero_intro" name="hero_intro" rows="3" required>{{ old('hero_intro', $settings['hero_intro'] ?? '') }}</textarea>@error('hero_intro')<span class="field-error">{{ $message }}</span>@enderror<label for="about_lead">About lead</label><input id="about_lead" name="about_lead" value="{{ old('about_lead', $settings['about_lead'] ?? '') }}" required>@error('about_lead')<span class="field-error">{{ $message }}</span>@enderror<label for="about_body">About description</label><textarea id="about_body" name="about_body" rows="5" required>{{ old('about_body', $settings['about_body'] ?? '') }}</textarea>@error('about_body')<span class="field-error">{{ $message }}</span>@enderror<label for="location">Location</label><input id="location" name="location" value="{{ old('location', $settings['location'] ?? '') }}">@error('location')<span class="field-error">{{ $message }}</span>@enderror<label for="cv_url">CV URL</label><input id="cv_url" name="cv_url" type="url" value="{{ old('cv_url', $settings['cv_url'] ?? '') }}">@error('cv_url')<span class="field-error">{{ $message }}</span>@enderror</section>
        <section class="admin-panel"><div class="panel-heading"><div><span class="sidebar-label">CONTACT &amp; LINKS</span><h2>Where to find you</h2></div></div><label for="contact_email">Contact email</label><input id="contact_email" name="contact_email" type="email" value="{{ old('contact_email', $settings['contact_email'] ?? '') }}">@error('contact_email')<span class="field-error">{{ $message }}</span>@enderror<label for="github_url">GitHub profile URL</label><input id="github_url" name="github_url" type="url" value="{{ old('github_url', $settings['github_url'] ?? '') }}">@error('github_url')<span class="field-error">{{ $message }}</span>@enderror<p class="help-text">Social profile cards are managed under Social links. Contact form messages are saved to the admin inbox; this form does not send email.</p></section>
        <section class="admin-panel"><div class="panel-heading"><div><span class="sidebar-label">SEARCH PREVIEW</span><h2>SEO metadata</h2></div></div><label for="site_description">Site description</label><textarea id="site_description" name="site_description" rows="2" required>{{ old('site_description', $settings['site_description'] ?? '') }}</textarea>@error('site_description')<span class="field-error">{{ $message }}</span>@enderror<label for="seo_title">SEO title</label><input id="seo_title" name="seo_title" value="{{ old('seo_title', $settings['seo_title'] ?? '') }}">@error('seo_title')<span class="field-error">{{ $message }}</span>@enderror<label for="seo_description">SEO description</label><textarea id="seo_description" name="seo_description" rows="2">{{ old('seo_description', $settings['seo_description'] ?? '') }}</textarea>@error('seo_description')<span class="field-error">{{ $message }}</span>@enderror</section>
        <button class="admin-button admin-button-primary" type="submit">Save site settings <span>↗</span></button>
    </form>
@endsection
