@extends('admin.layout')
@section('title', 'Analytics')
@section('content')
<div class="page-heading"><div><span class="sidebar-label">REAL VISITOR DATA</span><h1>Analytics</h1><p>Privacy-conscious activity collected from published portfolio pages.</p></div><a class="admin-button admin-button-quiet" href="{{ route('admin.analytics.export', array_merge(request()->query(), ['kind' => 'sessions'])) }}">Export CSV ↓</a></div>
@include('admin.analytics.filters')
<div class="analytics-tabs"><a href="{{ route('admin.analytics.overview') }}">Overview</a><a href="{{ route('admin.analytics.visitors') }}">Visitors</a><a href="{{ route('admin.analytics.sources') }}">Sources</a><a href="{{ route('admin.analytics.pages') }}">Pages</a><a href="{{ route('admin.analytics.events') }}">Events</a><a href="{{ route('admin.analytics.geography') }}">Geography</a><a href="{{ route('admin.analytics.realtime') }}">Live</a></div>
<div class="stat-cards analytics-stat-cards"><article><span>VISITORS</span><strong>{{ number_format($summary['visitors']) }}</strong><small>{{ number_format($summary['new_visitors']) }} new · {{ number_format($summary['returning_visitors']) }} returning</small></article><article><span>SESSIONS</span><strong>{{ number_format($summary['sessions']) }}</strong><small>Across selected dates</small></article><article><span>PAGE VIEWS</span><strong>{{ number_format($summary['page_views']) }}</strong><small>{{ $summary['avg_pages'] }} pages per session</small></article><article><span>BOUNCE RATE</span><strong>{{ $summary['bounce_rate'] }}%</strong><small>{{ gmdate('i:s', $summary['avg_duration']) }} average view duration</small></article></div>
<div class="analytics-grid"><section class="admin-panel analytics-chart-panel"><div class="panel-heading"><div><span class="sidebar-label">{{ $filters['from']->format('M j') }} – {{ $filters['to']->format('M j, Y') }}</span><h2>Page views over time</h2></div><span class="live-pill"><i></i>{{ number_format($summary['online']) }} online now</span></div>@if ($summary['daily']->isEmpty())<div class="empty-panel"><span>⌁</span><p>No visitor analytics yet. Real page views will appear here as people visit the published site.</p></div>@else<div class="analytics-bars" role="img" aria-label="Page views per day">@php($maxDaily = max(1, $summary['daily']->max('total')))<div class="analytics-svg-bars">@foreach ($summary['daily'] as $day)<div class="analytics-bar-wrap" title="{{ $day->day }}: {{ $day->total }} page views"><span style="height: {{ max(4, (int) round($day->total / $maxDaily * 100)) }}%"></span><small>{{ \Illuminate\Support\Carbon::parse($day->day)->format('j') }}</small></div>@endforeach</div></div>@endif</section>
<section class="admin-panel"><div class="panel-heading"><div><span class="sidebar-label">ACQUISITION</span><h2>Top sources</h2></div><a class="admin-text-link" href="{{ route('admin.analytics.sources') }}">All sources →</a></div>@forelse ($summary['sources'] as $row)<div class="analytics-rank"><span>{{ $row->label ?: 'Direct' }}</span><strong>{{ $row->total }}</strong></div>@empty<div class="empty-panel"><p>No source data yet.</p></div>@endforelse</section>
<section class="admin-panel"><div class="panel-heading"><div><span class="sidebar-label">CONTENT</span><h2>Popular pages</h2></div><a class="admin-text-link" href="{{ route('admin.analytics.pages') }}">All pages →</a></div>@forelse ($summary['popular_pages'] as $row)<a class="analytics-rank" href="{{ route('admin.analytics.page', ['path' => $row->path]) }}"><span>{{ $row->path }}</span><strong>{{ $row->total }}</strong></a>@empty<div class="empty-panel"><p>No page views yet.</p></div>@endforelse</section>
<section class="admin-panel"><div class="panel-heading"><div><span class="sidebar-label">PROJECT ENGAGEMENT</span><h2>Popular projects</h2></div><a class="admin-text-link" href="{{ route('admin.analytics.pages') }}">Project pages →</a></div>@forelse ($summary['popular_projects'] as $row)<a class="analytics-rank" href="{{ route('admin.analytics.page', ['path' => '/projects/'.$row->slug]) }}"><span>{{ $row->title }}</span><strong>{{ $row->total }}</strong></a>@empty<div class="empty-panel"><p>No project page views yet.</p></div>@endforelse</section>
<section class="admin-panel"><div class="panel-heading"><div><span class="sidebar-label">ENGAGEMENT</span><h2>Interactions</h2></div><a class="admin-text-link" href="{{ route('admin.analytics.events') }}">Event log →</a></div>@forelse ($summary['events'] as $row)<div class="analytics-rank"><span>{{ str_replace('_', ' ', ucfirst($row->event_name)) }}</span><strong>{{ $row->total }}</strong></div>@empty<div class="empty-panel"><p>No interactions recorded yet.</p></div>@endforelse</section>
<section class="admin-panel"><div class="panel-heading"><div><span class="sidebar-label">CONTACT CONVERSION</span><h2>Contact funnel</h2></div></div><div class="analytics-rank"><span>Contact section views</span><strong>{{ $summary['contact_section_views'] }}</strong></div><div class="analytics-rank"><span>Form starts</span><strong>{{ $summary['contact_form_starts'] }}</strong></div><div class="analytics-rank"><span>Successful submissions</span><strong>{{ $summary['contact_submissions'] }}</strong></div><div class="analytics-rank"><span>CV downloads</span><strong>{{ $summary['cv_downloads'] }}</strong></div></section>
<section class="admin-panel"><div class="panel-heading"><div><span class="sidebar-label">VISITORS</span><h2>Devices, browsers and locations</h2></div><a class="admin-text-link" href="{{ route('admin.analytics.geography') }}">Explore →</a></div><strong class="analytics-breakdown-label">Devices</strong>@forelse ($summary['devices'] as $row)<div class="analytics-rank"><span>{{ ucfirst($row->label) }}</span><strong>{{ $row->total }}</strong></div>@empty<div class="empty-panel"><p>No device data yet.</p></div>@endforelse<strong class="analytics-breakdown-label">Browsers</strong>@forelse ($summary['browsers'] as $row)<div class="analytics-rank"><span>{{ $row->label }}</span><strong>{{ $row->total }}</strong></div>@empty<div class="empty-panel"><p>No browser data yet.</p></div>@endforelse<strong class="analytics-breakdown-label">Operating systems</strong>@forelse ($summary['operating_systems'] as $row)<div class="analytics-rank"><span>{{ $row->label }}</span><strong>{{ $row->total }}</strong></div>@empty<div class="empty-panel"><p>No operating system data yet.</p></div>@endforelse<strong class="analytics-breakdown-label">Countries</strong>@forelse ($summary['countries'] as $row)<div class="analytics-rank"><span>{{ $row->label }}</span><strong>{{ $row->total }}</strong></div>@empty<div class="empty-panel"><p>Location is unknown until a local GeoLite2 City database is configured.</p></div>@endforelse</section></div>
<p class="analytics-privacy-note">Approximate location comes from the local MaxMind GeoLite2 database. Raw IP addresses, full browser strings, and form contents are never stored. Records are retained indefinitely.</p>
@endsection
