@extends('portfolio.layout')

@section('meta_title', 'Projects — '.($settings['site_title'] ?? 'Alif Utsho'))
@section('meta_description', 'Selected software projects and public repositories by '.($settings['site_title'] ?? 'Alif Utsho').'.')

@section('content')
    <section class="content-hero section-wrap"><span class="section-kicker">SELECTED WORK / PUBLIC REPOSITORIES</span><h1>Projects that show<br>the <span class="serif-word">work behind the work.</span></h1><p>Selected projects, with descriptions kept close to what their public repositories document.</p></section>
    <section class="section-wrap project-index-section"><div class="project-filters" role="group" aria-label="Filter projects"><button class="filter-button is-active" type="button" data-filter="all" aria-pressed="true">All work</button><button class="filter-button" type="button" data-filter="php" aria-pressed="false">PHP</button><button class="filter-button" type="button" data-filter="csharp" aria-pressed="false">ASP.NET / C#</button><button class="filter-button" type="button" data-filter="javascript" aria-pressed="false">JavaScript</button></div>
        @if ($projects->isNotEmpty())<div class="projects-grid">@foreach ($projects as $project)<article class="project-card {{ $loop->first ? 'project-featured' : '' }} reveal" data-category="{{ $project->metadata['category'] ?? 'other' }}"><a class="project-card-link" href="{{ route('projects.show', $project->slug) }}"><div class="project-art {{ $loop->first ? 'art-postbook' : 'art-postbook-net' }}">@if ($project->image_path)<img src="{{ Storage::disk('public')->url($project->image_path) }}" alt="{{ $project->metadata['alt_text'] ?? $project->title }}" loading="lazy">@else<div class="architecture-map"><div class="arch-box">{{ $project->technologies[0] ?? 'PROJECT' }}</div><span>↓</span><div class="arch-box arch-db">{{ $project->subtitle ?? 'APPLICATION' }}</div></div>@endif<span class="art-label">{{ $project->eyebrow ?? 'PROJECT' }}</span></div><div class="project-info"><div class="project-title-row"><div><span class="project-type">{{ $project->eyebrow ?? 'PROJECT' }}</span><h2>{{ $project->title }}</h2></div><span class="project-arrow" aria-hidden="true">↗</span></div><p>{{ $project->summary }}</p><div class="tag-row">@foreach ($project->technologies ?? [] as $technology)<span>{{ $technology }}</span>@endforeach</div></div></a></article>@endforeach</div><div class="pagination-wrap">{{ $projects->links() }}</div>@else<div class="empty-state"><h2>Projects are being prepared.</h2><p>Check back soon for selected work.</p></div>@endif
    </section>
@endsection
