@extends('portfolio.layout')
@section('analytics_project_id', $project->id)

@section('meta_title', $project->title.' — '.($settings['site_title'] ?? 'Alif Utsho'))
@section('meta_description', $project->summary ?: $project->title.' — selected project by '.($settings['site_title'] ?? 'Alif Utsho').'.')

@section('content')
    <section class="project-detail-hero section-wrap"><a class="back-link" href="{{ route('projects.index') }}">← All projects</a><span class="section-kicker">{{ strtoupper($project->eyebrow ?? 'SELECTED PROJECT') }}</span><h1>{{ $project->title }}</h1><p class="project-detail-summary">{{ $project->summary }}</p><div class="tag-row">@foreach ($project->technologies ?? [] as $technology)<span>{{ $technology }}</span>@endforeach</div></section>
    @if ($project->image_path)<section class="section-wrap detail-image"><img src="{{ Storage::disk('public')->url($project->image_path) }}" alt="{{ $project->metadata['alt_text'] ?? $project->title }}"></section>@endif
    <section class="section-wrap project-detail-body"><article class="detail-copy"><span class="section-kicker">PROJECT NOTES</span><div class="prose-copy">@if ($project->body)<p>{{ $project->body }}</p>@endif @if ($project->metadata['challenge'] ?? null)<h2>Problem space</h2><p>{{ $project->metadata['challenge'] }}</p>@endif @if ($project->metadata['features'] ?? [])<h2>Repository notes</h2><ul>@foreach ($project->metadata['features'] as $feature)<li>{{ $feature }}</li>@endforeach</ul>@endif</div></article><aside class="detail-aside"><div><span>PROJECT</span><strong>{{ $project->title }}</strong></div>@if ($project->subtitle)<div><span>CONTEXT</span><strong>{{ $project->subtitle }}</strong></div>@endif<div><span>TECHNOLOGIES</span><div class="tag-row">@foreach ($project->technologies ?? [] as $technology)<span>{{ $technology }}</span>@endforeach</div></div><div class="detail-links">@if ($project->url)<a class="button button-primary" href="{{ $project->url }}" target="_blank" rel="noreferrer">View repository <span>↗</span></a>@endif @if ($project->secondary_url)<a class="button button-quiet" href="{{ $project->secondary_url }}" target="_blank" rel="noreferrer">Live project <span>↗</span></a>@endif</div></aside></section>
    @if ($relatedProjects->isNotEmpty())<section class="section-wrap related-projects"><div class="section-heading"><span class="section-kicker">KEEP EXPLORING</span><h2>More selected <span class="serif-word">work.</span></h2></div><div class="projects-grid">@foreach ($relatedProjects as $related)<article class="project-card reveal"><a href="{{ route('projects.show', $related->slug) }}"><div class="project-info"><span class="project-type">{{ $related->eyebrow ?? 'PROJECT' }}</span><h3>{{ $related->title }}</h3><p>{{ $related->summary }}</p><span class="text-link">Project details <span>↗</span></span></div></a></article>@endforeach</div></section>@endif
@endsection
